import express from 'express';
import { body, validationResult } from 'express-validator';
import Exam from '../models/Exam.js';
import Question from '../models/Question.js';
import ExamResult from '../models/ExamResult.js';
import Response from '../models/Response.js';
import { protect, authorizeRole } from '../middleware/auth.js';

const router = express.Router();

function getExamWindow(exam) {
  const examDate = new Date(exam.examDate);

  // Set start to beginning of the day (00:00:00.000)
  const startOfDay = new Date(examDate);
  startOfDay.setHours(0, 0, 0, 0);

  // Set end to end of the day (23:59:59.999)
  const endOfDay = new Date(examDate);
  endOfDay.setHours(23, 59, 59, 999);

  return { examStart: startOfDay, examEnd: endOfDay, examDate };
}

// @route   POST /api/exams
// @desc    Create a new exam
// @access  Private/Teacher
router.post(
  '/',
  [
    protect,
    authorizeRole('teacher'),
    body('title').notEmpty().withMessage('Title is required'),
    body('examDate').isISO8601().withMessage('Valid exam date is required'),
    body('durationMinutes').isInt({ min: 1 }).withMessage('Duration must be at least 1 minute')
  ],
  async (req, res) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        console.log('Validation errors:', errors.array());
        return res.status(400).json({ errors: errors.array() });
      }

      const { title, description, examDate, durationMinutes } = req.body;

      console.log('Creating exam with data:', { title, description, examDate, durationMinutes, teacherId: req.user._id });

      const exam = await Exam.create({
        title,
        description,
        examDate,
        durationMinutes,
        teacherId: req.user._id
        // examCode will be auto-generated by pre-save hook
      });

      console.log('Exam created successfully:', exam._id);
      res.status(201).json(exam);
    } catch (error) {
      console.error('❌ Error creating exam:', error.message);
      console.error('Full error:', error);
      res.status(500).json({ message: error.message || 'Server error' });
    }
  }
);

// @route   GET /api/exams
// @desc    Get all exams for the logged in teacher
// @access  Private/Teacher
router.get('/', protect, authorizeRole('teacher'), async (req, res) => {
  try {
    const exams = await Exam.find({ teacherId: req.user._id }).sort({ createdAt: -1 });
    res.json(exams);
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: 'Server error' });
  }
});

// @route   DELETE /api/exams/:id
// @desc    Delete exam by ID
// @access  Private/Teacher
router.delete('/:id', protect, authorizeRole('teacher'), async (req, res) => {
  try {
    const exam = await Exam.findById(req.params.id);

    if (!exam) {
      return res.status(404).json({ message: 'Exam not found' });
    }

    if (exam.teacherId.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Not authorized to delete this exam' });
    }

    await Promise.all([
      Question.deleteMany({ examId: exam._id }),
      ExamResult.deleteMany({ examId: exam._id }),
      Response.deleteMany({ examId: exam._id }),
      Exam.findByIdAndDelete(exam._id)
    ]);

    res.json({ message: 'Exam deleted successfully' });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: 'Server error' });
  }
});

// @route   GET /api/exams/:id
// @desc    Get exam by ID
// @access  Private
router.get('/:id', protect, async (req, res) => {
  try {
    const exam = await Exam.findById(req.params.id);

    if (!exam) {
      return res.status(404).json({ message: 'Exam not found' });
    }

    // Check if student is trying to access a future exam
    if (req.user.role === 'student') {
      const now = new Date();
      const { examStart, examEnd, examDate } = getExamWindow(exam);

      if (now < examStart) {
        return res.status(400).json({
          message: `This exam is scheduled for ${examDate.toLocaleDateString()} and is not yet open.`
        });
      }

      if (now > examEnd) {
        return res.status(400).json({
          message: `This exam has already ended. It was scheduled for ${examDate.toLocaleDateString()} with a duration of ${exam.durationMinutes} minutes.`
        });
      }
    }

    res.json(exam);
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: 'Server error' });
  }
});

// @route   GET /api/exams/code/:code
// @desc    Get exam by exam code
// @access  Private/Student
router.get('/code/:code', protect, authorizeRole('student'), async (req, res) => {
  try {
    const exam = await Exam.findOne({ examCode: req.params.code.toUpperCase() });

    if (!exam) {
      return res.status(404).json({ message: 'Exam not found' });
    }

    // Check if student has already taken this exam
    const existingResult = await ExamResult.findOne({
      studentId: req.user._id,
      examId: exam._id
    });

    if (existingResult) {
      return res.status(400).json({ message: 'You have already taken this exam' });
    }

    // Check if exam is in the future
    const now = new Date();
    const { examStart, examEnd, examDate } = getExamWindow(exam);

    if (now < examStart) {
      return res.status(400).json({
        message: `This exam is scheduled for ${examDate.toLocaleDateString()} and is not yet open.`
      });
    }

    if (now > examEnd) {
      return res.status(400).json({
        message: `This exam has already ended. It was scheduled for ${examDate.toLocaleDateString()} with a duration of ${exam.durationMinutes} minutes.`
      });
    }

    res.json(exam);
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: 'Server error' });
  }
});

export default router;
